# name your workflow
name: random data

# definy the frequency it'll run
on:
  schedule:
    - cron: "0 0 * * 0" # every sunday at midnight
  workflow_dispatch:

env:
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true

# create the jobs
jobs:
  generate-latest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' # setting python version to 3.10
      - name: Install requirements
        run: pip3 install -r requirements.txt # setting the environment
      - name: Run random data
        run: python main.py
      - name: Commit and push changes
        run: |
          git config --global user.name "devmedeiros"
          git config --global user.email "medeirosestatistica@gmail.com"

          git add -A
          git commit -m "add more data"
          git push
